### ISSUE TITLE
O-Net error?

### ISSUE THREAD

**Issue by richipower** [foreverYoungGitHub/MTCNN#10]
Hello! i try to get it running under windows, it runs normally and then closes unexpectedly when entering the O-Net phase.. using the  MTCNN::detection_TEST function.. some one experiencing the same? or do you know what could be going wrong @foreverYoungGitHub ? i will try to debug it later :)
cheers!

**Comment by foreverYoungGitHub** [comment]
I have test the code in the visual studio. It works fine.

Can you specify your situation and show the log?

**Comment by richipower** [comment]
i downloaded the newer version of the code and now its working :)
