### ISSUE TITLE
image label calculate

### ISSUE THREAD

**Issue by wuzhiyang2016** [foreverYoungGitHub/MTCNN#13]
hei Liuyang many thanks for you . but how to calculate the face regression train labels? as you give-- face regression: [0.1,0.1,0.1,0.1].,,what‘s the calculation method to get these values: 0.1 0.1 0.1 0.1

**Comment by wuzhiyang2016** [comment]
@foreverYoungGitHub  could you give me an example?

**Comment by foreverYoungGitHub** [comment]
This is the inverse calculation for the face regression in the test phase.

When the IoU of the candidate window and  the ground truth is higher than 0.4, we think candidate window has overlapped part of the face.

In this situation, we calculate the four deviation values for the candidate window to let them close to the ground truth. These four deviation values are the proportional offset for the left, top, right and hight of the candidate window.

For example, if the width of the  candidate window is ``(W, H)``. The coordinates of left top point of the candidate window and the ground truth are ``(L_c, T_c)`` and ``(L_g, T_g)``. So the regression value of the left and top are ``\frac{L_g - L_c}{W}`` and ``\frac{T_g - T_c}{H}``.
