### ISSUE TITLE
CelebA数据库如何生成训练数据

### ISSUE THREAD

**Issue by zgq91** [foreverYoungGitHub/MTCNN#17]
你好：
       请问你是如何将CelebA数据库生成 你 generate_hdf5.py中的
label_path = '../dataset/label.txt'
landmark_path = '../dataset/landmark.txt'
regression_box_path = '../dataset/regression_box.txt'
crop_image_path = '../dataset/crop_image.txt'
train_file_path = '../dataset/train_24.hd5'
caffe菜鸟,期待你的回复  谢谢

**Comment by foreverYoungGitHub** [comment]
A demo crop program is shown in /master/script/train_sh/celeba_crop folder.

However, this program only crop the positive sample for training and testing, you need to revise it to generate the negative sample.

Best wishes,

Yang

**Comment by sunjunlishi** [comment]
意思是txt中的内容是啥，然后脚本生成的内容大致是啥，如何被神经网络读取，万分感谢
