### ISSUE TITLE
three types train data's proportion

### ISSUE THREAD

**Issue by wuzhiyang2016** [foreverYoungGitHub/MTCNN#19]
hi, @foreverYoungGitHub , what's the proprotion of  three types train data?  positive : part : negative= ? :? :?

**Comment by foreverYoungGitHub** [comment]
The positive : negative always keeps 1 : 3, while "part" image is keeping increasing.

For example, the positive : part : negative= 1 : 3 : 3 at the beginning, while it will change to positive : part : negative= 1 : 5 : 3 in the next iteration.

If you want to use to pre-trained weight to train your net, it would be better to have the higher proportion in part face.
