### ISSUE TITLE
x y w h ?

### ISSUE THREAD

**Issue by wuzhiyang2016** [foreverYoungGitHub/MTCNN#21]
@foreverYoungGitHub   Hi yang,  what's your train label.  is  x y w h  or  x1 y1 x2,y2?

**Comment by foreverYoungGitHub** [comment]
I labelled the train set as x y w h.

**Comment by wuzhiyang2016** [comment]
Hi,  In MTCNN.cpp, why  //regression box : y x height width    **instead of**     x y w h ?

**Comment by wuzhiyang2016** [comment]
@foreverYoungGitHub
