### ISSUE TITLE
the code can be used to train mtcnn model?

### ISSUE THREAD

**Issue by Cv9527** [foreverYoungGitHub/MTCNN#3]
@foreverYoungGitHub thx share the code, can the code be used to train mtcnn model?

**Comment by foreverYoungGitHub** [comment]
When you need to prepare your database and use the generate_hdf5.py file to generate hdf5 file. Change the prototype file and train your model by yourself.

**Comment by foreverYoungGitHub** [comment]
I'll update the readme and show how to train a model by yourself
