### ISSUE TITLE
compare erreo

### ISSUE THREAD

**Issue by mathpopo** [foreverYoungGitHub/MTCNN#63]
In file included from /home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:9:0:
/home/chenxin/Downloads/MTCNN/detection/MTCNN.h:55:33: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp> class std::shared_ptr’
     std::vector<std::shared_ptr<Net>> nets_;
                                 ^~~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.h:55:33: note:   expected a type, got ‘Net’
/home/chenxin/Downloads/MTCNN/detection/MTCNN.h:55:36: error: template argument 1 is invalid
     std::vector<std::shared_ptr<Net>> nets_;
                                    ^~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.h:55:36: error: template argument 2 is invalid
In file included from /home/chenxin/Downloads/MTCNN/detection/main.cpp:2:0:
/home/chenxin/Downloads/MTCNN/detection/MTCNN.h:55:33: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp> class std::shared_ptr’
     std::vector<std::shared_ptr<Net>> nets_;
                                 ^~~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.h:55:33: note:   expected a type, got ‘Net’
/home/chenxin/Downloads/MTCNN/detection/MTCNN.h:55:36: error: template argument 1 is invalid
     std::vector<std::shared_ptr<Net>> nets_;
                                    ^~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.h:55:36: error: template argument 2 is invalid
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp: In constructor ‘MTCNN::MTCNN(std::vector<std::__cxx11::basic_string<char> >, std::vector<std::__cxx11::basic_string<char> >)’:
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:18:9: error: ‘SetMode’ is not a member of ‘caffe’
         caffe::SetMode(caffe::GPU, 0);
         ^~~~~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:18:24: error: ‘GPU’ is not a member of ‘caffe’
         caffe::SetMode(caffe::GPU, 0);
                        ^~~~~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:24:28: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp> class std::shared_ptr’
         std::shared_ptr<Net> net;
                            ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:24:28: note:   expected a type, got ‘Net’
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:29:13: error: request for member ‘reset’ in ‘net’, which is of non-class type ‘int’
         net.reset(new Net(model_file[i]));
             ^~~~~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:29:23: error: expected type-specifier before ‘Net’
         net.reset(new Net(model_file[i]));
                       ^~~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:30:12: error: base operand of ‘->’ is not a pointer
         net->CopyTrainedLayersFrom(trained_file[i]);
            ^~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:32:13: error: missing template arguments before ‘*’ token
         Blob* input_layer = net->blob_by_name("data").get();
             ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:32:15: error: ‘input_layer’ was not declared in this scope
         Blob* input_layer = net->blob_by_name("data").get();
               ^~~~~~~~~~~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:32:32: error: base operand of ‘->’ is not a pointer
         Blob* input_layer = net->blob_by_name("data").get();
                                ^~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:36:15: error: request for member ‘push_back’ in ‘((MTCNN*)this)->MTCNN::nets_’, which is of non-class type ‘int’
         nets_.push_back(net);
               ^~~~~~~~~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp: In member function ‘void MTCNN::Predict(const cv::Mat&, int)’:
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:335:24: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp> class std::shared_ptr’
     std::shared_ptr<Net> net = nets_[i];
                        ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:335:24: note:   expected a type, got ‘Net’
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:335:39: error: invalid types ‘int[int]’ for array subscript
     std::shared_ptr<Net> net = nets_[i];
                                       ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:338:9: error: missing template arguments before ‘*’ token
     Blob* input_layer = net->blob_by_name("data").get();
         ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:338:11: error: ‘input_layer’ was not declared in this scope
     Blob* input_layer = net->blob_by_name("data").get();
           ^~~~~~~~~~~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:338:28: error: base operand of ‘->’ is not a pointer
     Blob* input_layer = net->blob_by_name("data").get();
                            ^~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:342:8: error: base operand of ‘->’ is not a pointer
     net->Reshape();
        ^~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:346:8: error: base operand of ‘->’ is not a pointer
     net->Forward();
        ^~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:349:9: error: missing template arguments before ‘*’ token
     Blob* rect = net->blob_by_name(output_blob_names[0]).get();
         ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:349:11: error: ‘rect’ was not declared in this scope
     Blob* rect = net->blob_by_name(output_blob_names[0]).get();
           ^~~~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:349:21: error: base operand of ‘->’ is not a pointer
     Blob* rect = net->blob_by_name(output_blob_names[0]).get();
                     ^~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:350:9: error: missing template arguments before ‘*’ token
     Blob* confidence = net->blob_by_name(output_blob_names[1]).get();
         ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:350:11: error: ‘confidence’ was not declared in this scope
     Blob* confidence = net->blob_by_name(output_blob_names[1]).get();
           ^~~~~~~~~~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:350:27: error: base operand of ‘->’ is not a pointer
     Blob* confidence = net->blob_by_name(output_blob_names[1]).get();
                           ^~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp: In member function ‘void MTCNN::Predict(std::vector<cv::Mat>, int)’:
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:370:24: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp> class std::shared_ptr’
     std::shared_ptr<Net> net = nets_[i];
                        ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:370:24: note:   expected a type, got ‘Net’
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:370:39: error: invalid types ‘int[int]’ for array subscript
     std::shared_ptr<Net> net = nets_[i];
                                       ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:373:9: error: missing template arguments before ‘*’ token
     Blob* input_layer = net->blob_by_name("data").get();
         ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:373:11: error: ‘input_layer’ was not declared in this scope
     Blob* input_layer = net->blob_by_name("data").get();
           ^~~~~~~~~~~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:373:28: error: base operand of ‘->’ is not a pointer
     Blob* input_layer = net->blob_by_name("data").get();
                            ^~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:378:8: error: base operand of ‘->’ is not a pointer
     net->Reshape();
        ^~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:383:8: error: base operand of ‘->’ is not a pointer
     net->Forward();
        ^~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:389:9: error: missing template arguments before ‘*’ token
     Blob* confidence = net->blob_by_name(output_blob_names[i]).get();
         ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:389:11: error: ‘confidence’ was not declared in this scope
     Blob* confidence = net->blob_by_name(output_blob_names[i]).get();
           ^~~~~~~~~~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:389:27: error: base operand of ‘->’ is not a pointer
     Blob* confidence = net->blob_by_name(output_blob_names[i]).get();
                           ^~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:396:9: error: missing template arguments before ‘*’ token
     Blob* rect = net->blob_by_name(output_blob_names[0]).get();
         ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:396:11: error: ‘rect’ was not declared in this scope
     Blob* rect = net->blob_by_name(output_blob_names[0]).get();
           ^~~~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:396:21: error: base operand of ‘->’ is not a pointer
     Blob* rect = net->blob_by_name(output_blob_names[0]).get();
                     ^~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:403:13: error: missing template arguments before ‘*’ token
         Blob* points = net->blob_by_name(output_blob_names[1]).get();
             ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:403:15: error: ‘points’ was not declared in this scope
         Blob* points = net->blob_by_name(output_blob_names[1]).get();
               ^~~~~~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:403:27: error: base operand of ‘->’ is not a pointer
         Blob* points = net->blob_by_name(output_blob_names[1]).get();
                           ^~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp: In member function ‘void MTCNN::WrapInputLayer(const cv::Mat&, std::vector<cv::Mat>*, int)’:
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:412:9: error: missing template arguments before ‘*’ token
     Blob* input_layer = nets_[i]->blob_by_name("data").get();
         ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:412:11: error: ‘input_layer’ was not declared in this scope
     Blob* input_layer = nets_[i]->blob_by_name("data").get();
           ^~~~~~~~~~~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:412:32: error: invalid types ‘int[int]’ for array subscript
     Blob* input_layer = nets_[i]->blob_by_name("data").get();
                                ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp: In member function ‘void MTCNN::WrapInputLayer(std::vector<cv::Mat>, std::vector<cv::Mat>*, int)’:
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:439:10: error: missing template arguments before ‘*’ token
     Blob *input_layer = nets_[i]->blob_by_name("data").get();
          ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:439:11: error: ‘input_layer’ was not declared in this scope
     Blob *input_layer = nets_[i]->blob_by_name("data").get();
           ^~~~~~~~~~~
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:439:32: error: invalid types ‘int[int]’ for array subscript
     Blob *input_layer = nets_[i]->blob_by_name("data").get();
                                ^
CMakeFiles/MTCNN.dir/build.make:82: recipe for target 'CMakeFiles/MTCNN.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/MTCNN.dir/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/MTCNN.dir/build.make:95: recipe for target 'CMakeFiles/MTCNN.dir/MTCNN.cpp.o' failed
make[2]: *** [CMakeFiles/MTCNN.dir/MTCNN.cpp.o] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/MTCNN.dir/all' failed
make[1]: *** [CMakeFiles/MTCNN.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mathpopo** [comment]
@foreverYoungGitHub  plz help me ,is it a env issue?using gcc or clang?

**Comment by mathpopo** [comment]
-- Configuring done
-- Generating done
-- Build files have been written to: /home/chenxin/Downloads/MTCNN/detection/cmake-build-debug
[ 33%] Building CXX object CMakeFiles/MTCNN.dir/main.cpp.o
[ 66%] Building CXX object CMakeFiles/MTCNN.dir/MTCNN.cpp.o
In file included from /home/chenxin/Downloads/MTCNN/detection/MTCNN.cppIn file included from :/home/chenxin/Downloads/MTCNN/detection/main.cpp9::
2:
/home/chenxin/Downloads/MTCNN/detection/MTCNN.h:/home/chenxin/Downloads/MTCNN/detection/MTCNN.h55::5533::33 : error: error: use of class template 'Net' requires template argumentsuse of class template 'Net' requires template arguments

    std::vector<std::shared_ptr<Net>> nets_;    std::vector<std::shared_ptr<Net>> nets_;

                                ^                                ^

/home/chenxin/Downloads/caffe/include/caffe/net.hpp/home/chenxin/Downloads/caffe/include/caffe/net.hpp::2424::77::  notenote: : template is declared heretemplate is declared here

class Net {class Net {

      ^      ^

/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:18:16: error: no member named 'SetMode' in namespace 'caffe'
        caffe::SetMode(caffe::GPU, 0);
        ~~~~~~~^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:18:31: error: no member named 'GPU' in namespace 'caffe'
        caffe::SetMode(caffe::GPU, 0);
                       ~~~~~~~^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:24:25: error: use of class template 'Net' requires template arguments
        std::shared_ptr<Net> net;
                        ^
/home/chenxin/Downloads/caffe/include/caffe/net.hpp:24:7: note: template is declared here
class Net {
      ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:29:23: error: use of class template 'Net' requires template arguments
        net.reset(new Net(model_file[i]));
                      ^
/home/chenxin/Downloads/caffe/include/caffe/net.hpp:24:7: note: template is declared here
class Net {
      ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:32:9: error: use of class template 'Blob' requires template arguments
        Blob* input_layer = net->blob_by_name("data").get();
        ^
/home/chenxin/Downloads/caffe/include/caffe/blob.hpp:24:7: note: template is declared here
class Blob {
      ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:189:21: warning: unused variable 'a' [-Wunused-variable]
                int a = 0;
                    ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:246:23: warning: unused variable 'a' [-Wunused-variable]
                float a = IoU(cur_rects[i], cur_rects[j]);
                      ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:335:21: error: use of class template 'Net' requires template arguments
    std::shared_ptr<Net> net = nets_[i];
                    ^
/home/chenxin/Downloads/caffe/include/caffe/net.hpp:24:7: note: template is declared here
class Net {
      ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:338:5: error: use of class template 'Blob' requires template arguments
    Blob* input_layer = net->blob_by_name("data").get();
    ^
/home/chenxin/Downloads/caffe/include/caffe/blob.hpp:24:7: note: template is declared here
class Blob {
      ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:349:5: error: use of class template 'Blob' requires template arguments
    Blob* rect = net->blob_by_name(output_blob_names[0]).get();
    ^
/home/chenxin/Downloads/caffe/include/caffe/blob.hpp:24:7: note: template is declared here
class Blob {
      ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:350:5: error: use of class template 'Blob' requires template arguments
    Blob* confidence = net->blob_by_name(output_blob_names[1]).get();
    ^
/home/chenxin/Downloads/caffe/include/caffe/blob.hpp:24:7: note: template is declared here
class Blob {
      ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:370:21: error: use of class template 'Net' requires template arguments
    std::shared_ptr<Net> net = nets_[i];
                    ^
/home/chenxin/Downloads/caffe/include/caffe/net.hpp:24:7: note: template is declared here
class Net {
      ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:373:5: error: use of class template 'Blob' requires template arguments
    Blob* input_layer = net->blob_by_name("data").get();
    ^
/home/chenxin/Downloads/caffe/include/caffe/blob.hpp:24:7: note: template is declared here
class Blob {
      ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:389:5: error: use of class template 'Blob' requires template arguments
    Blob* confidence = net->blob_by_name(output_blob_names[i]).get();
    ^
/home/chenxin/Downloads/caffe/include/caffe/blob.hpp:24:7: note: template is declared here
class Blob {
      ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:396:5: error: use of class template 'Blob' requires template arguments
    Blob* rect = net->blob_by_name(output_blob_names[0]).get();
    ^
/home/chenxin/Downloads/caffe/include/caffe/blob.hpp:24:7: note: template is declared here
class Blob {
      ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:403:9: error: use of class template 'Blob' requires template arguments
        Blob* points = net->blob_by_name(output_blob_names[1]).get();
        ^
/home/chenxin/Downloads/caffe/include/caffe/blob.hpp:24:7: note: template is declared here
class Blob {
      ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:412:5: error: use of class template 'Blob' requires template arguments
    Blob* input_layer = nets_[i]->blob_by_name("data").get();
    ^
/home/chenxin/Downloads/caffe/include/caffe/blob.hpp:24:7: note: template is declared here
class Blob {
      ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:439:5: error: use of class template 'Blob' requires template arguments
    Blob *input_layer = nets_[i]->blob_by_name("data").get();
    ^
/home/chenxin/Downloads/caffe/include/caffe/blob.hpp:24:7: note: template is declared here
class Blob {
      ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:548:17: warning: unused variable 'a' [-Wunused-variable]
            int a = 0;
                ^
/home/chenxin/Downloads/MTCNN/detection/MTCNN.cpp:516:9: warning: unused variable 'feature_map_h' [-Wunused-variable]
    int feature_map_h = std::ceil((image_h - cellSize)*1.0/stride)+1;
        ^
1 error generated.
CMakeFiles/MTCNN.dir/build.make:82: recipe for target 'CMakeFiles/MTCNN.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/MTCNN.dir/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
4 warnings and 17 errors generated.
CMakeFiles/MTCNN.dir/build.make:95: recipe for target 'CMakeFiles/MTCNN.dir/MTCNN.cpp.o' failed
SET (CMAKE_CXX_COMPILER             "/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++")

also have issue

make[2]: *** [CMakeFiles/MTCNN.dir/MTCNN.cpp.o] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/MTCNN.dir/all' failed
make[1]: *** [CMakeFiles/MTCNN.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by foreverYoungGitHub** [comment]
Hi, @mathpopo. I'm sorry that this lib is not maintained anymore. And since I do not have caffe lib in my computer, I cannot reproduce this error.

If you are looking for the inference model for face detection, I would suggest that you can use any tf/pytorch model like [this one](https://github.com/timesler/facenet-pytorch) and convert it to tensorrt or other inference framework to achieved the best performance.

**Comment by mathpopo** [comment]
@foreverYoungGitHub  first thank you for you help, i just need a C++ ENV demo.https://github.com/timesler/facenet-pytorch  is base on python,

**Comment by foreverYoungGitHub** [comment]
You can convert it to tensorrt model, and use the tensorrt cpp code to inference framework and achieve the best performance. Some sample code can be found at here: https://foreveryounggithub.github.io/2020/06/17/trt_preproc_npp/.

**Comment by mathpopo** [comment]
@foreverYoungGitHub ok  i will try
