### ISSUE TITLE
pts loss 层 如何忽略负样本

### ISSUE THREAD

**Issue by wadesunyang** [foreverYoungGitHub/MTCNN#8]
数据处理时，我最终为下面的格式：（每行：图片位置  1个label  4个box 10个landmark）
pos1.jpg 1 0.1 0.2 0.3 0.4 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 
neg1.jpg 0 -1 -1 -1 -1  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 
part1.jpg -1 0.1 0.2 0.3 0.4 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 
landmark1.jpg -1 -1  -1 -1 -1  0.1  0.3 0.3 0.4 0.5 0.5 0.3 0.2 0.7 0.7
我在算landmark loss层时，如何忽略其他样本，您是重写的loss层么还是？   看prototxt您并没有重写，还是我前面忽略了什么信息，谢谢。

**Comment by luhairong11** [comment]
方便留下联系方式吗，我最近也在训练
